# Dockerfile for Laravel PHP 7.4 application with PHP-FPM
FROM php:7.4-fpm

# Arguments passed from docker-compose.yml file
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libfreetype6-dev \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libmagickwand-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd soap pdo_mysql intl 

# Install dependencies for Imagick extension
RUN apt-get update && apt-get install -y libmagickwand-dev libzip-dev

# Install Imagick extension
RUN pecl install imagick \
 && docker-php-ext-enable imagick

# Install Zip extension
RUN docker-php-ext-install zip

# Install npm and node
RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm

# Update npm and node to latest version
RUN npm install npm@latest -g && \
    npm install n -g && \
    n 16.13.1 

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www

# Copy contents of current directory to /var/www with correct permissions
COPY --chown=$user:$user . /var/www

# Set ownership of /var/www to the system user
RUN chown -R $user:$user /var/www

# Change current user to the system user
USER $user

# Run composer install, generate laravel app key, and install npm packages
RUN composer install && \ 
    php artisan key:generate && \
    npm install

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Start PHP-FPM server
CMD ["php-fpm"]
